<?php
/*
 * Your installation or use of this SugarCRM file is subject to the applicable
 * terms available at
 * http://support.sugarcrm.com/06_Customer_Center/10_Master_Subscription_Agreements/.
 * If you do not agree to all of the applicable terms or do not have the
 * authority to bind the entity as an authorized representative, then do not
 * install or use this SugarCRM file.
 *
 * Copyright (C) SugarCRM Inc. All rights reserved.
 */

// THIS CONTENT IS GENERATED BY MBPackage.php
$manifest = array (
  'built_in_version' => '7.7.1.2',
  'acceptable_sugar_versions' => 
  array (
    0 => '',
  ),
  'acceptable_sugar_flavors' => 
  array (
    0 => 'PRO',
    1 => 'CORP',
    2 => 'ENT',
    3 => 'ULT',
  ),
  'readme' => '',
  'key' => 'rt2',
  'author' => '',
  'description' => '',
  'icon' => '',
  'is_uninstallable' => true,
  'name' => 'Package_Two',
  'published_date' => '2017-07-27 07:10:00',
  'type' => 'module',
  'version' => 1501139400,
  'remove_tables' => 'prompt',
);


$installdefs = array (
  'id' => 'Package_Two',
  'beans' => 
  array (
    0 => 
    array (
      'module' => 'rt2_M1',
      'class' => 'rt2_M1',
      'path' => 'modules/rt2_M1/rt2_M1.php',
      'tab' => true,
    ),
    1 => 
    array (
      'module' => 'rt2_M2',
      'class' => 'rt2_M2',
      'path' => 'modules/rt2_M2/rt2_M2.php',
      'tab' => true,
    ),
  ),
  'layoutdefs' => 
  array (
  ),
  'relationships' => 
  array (
  ),
  'image_dir' => '<basepath>/icons',
  'copy' => 
  array (
    0 => 
    array (
      'from' => '<basepath>/SugarModules/modules/rt2_M1',
      'to' => 'modules/rt2_M1',
    ),
    1 => 
    array (
      'from' => '<basepath>/SugarModules/modules/rt2_M2',
      'to' => 'modules/rt2_M2',
    ),
  ),
  'language' => 
  array (
    0 => 
    array (
      'from' => '<basepath>/SugarModules/language/application/en_us.lang.php',
      'to_module' => 'application',
      'language' => 'en_us',
    ),
  ),
);